### PR TITLE
Created example which includes Calcite Components, Calcite App Compon…

### PR DESCRIPTION
**Pull request by rslibed**
…ents, and Webpack

### CODE REVIEW

**Comment by kellyhutchins** [comment]
@rslibed  looks good. There are a few more changes I plan on making to the application-base logic but I'll merge those into the application-base repo and then we can update this.

**Comment by kellyhutchins** [comment]
@rslibed  One enhancement that might be nice would be to extend this sample to use the calcite-app-components to have a simple layout (header, footer, and left or right panel) just as a 'getting started' demo app

**Comment by rslibed** [comment]
Created a layout with `calcite-modal`, `calcite-button`, `calcite-shell`, `calcite-shell-panel`, `calcite-block`, and `calcite-section`.

image

image

**Comment by kellyhutchins** [comment]
Looks good @rslibed  go ahead and merge when ready.

**Pull request merged**
